import numpy as np
import matplotlib.pyplot as plt
import codecs  # To open the file in specific mode

# Declaring two empty lists. One for words and one for their corresponding vector representation
words = []
vecs = []

vocabulary = []
wv = []

# Getting word and corresponding vector from each line of the model.vec file generated by fasttext
with codecs.open('model.vec', 'r', 'utf-8') as f_in:
    # vocabulary, wv = zip(*[line.strip().split(' ', maxsplit=1) for line in f_in])
    pairs = [line.strip().split(' ', maxsplit=1) for line in f_in]
    for pair in pairs:
        try:
            a, b = pair
            vocabulary.append(a)
            wv.append(b)
        except Exception:
            pass

# Populating the two lists. Need to convert vector values from string to numpy array

for i in range(10, len(vocabulary)):  # Usually skip first 10 words becuase they might be garbage values.
    words.append(vocabulary[i])
    x = wv[i]
    vecs.append(np.fromstring(x, dtype='float32', sep=' '))
    # np.fromstring takes string values and converts to float32 with space as a separator
print(vecs)
# vecs = np.array(vecs)
# print(vecs)

U, s, Vh = np.linalg.svd(vecs, full_matrices=False)

# Plotting words and their vector representations

for i in range(len(words)):
    fig = plt.gcf()
    fig.set_size_inches(18.5, 10.5)
    plt.text(U[i, 0], U[i, 1], words[i])
    plt.xlim((-0.5, 0.5))
    plt.ylim((-0.5, 0.5))

plt.savefig('viz.jpg')
