import numpy as np
import matplotlib.pyplot as plt
import codecs  # To open the file in specific mode

# Declaring two empty lists. One for words and one for their corresponding vector representation
reviews = []
vecs = []

sentences = []
wv = []

# Getting word and corresponding vector from each line of the model.vec file generated by fasttext
with codecs.open('model.vec', 'r', 'utf-8') as f_in:
    # vocabulary, wv = zip(*[line.strip().split(' ', maxsplit=1) for line in f_in])
    pairs = [line.split(' ', maxsplit=1) for line in f_in]
    for pair in pairs:
        try:
            a, b = pair
        except Exception:
            pass
        vocabulary.append(a)
        wv.append(b)

# Populating the two lists. Need to convert vector values from string to numpy array

for i in range(10, len(vocabulary)):  # Usually skip first 10 words becuase they might be garbage values.
    words.append(vocabulary[i])
    x = wv[i]
    vecs.append(np.fromstring(x, dtype='float32', sep=' '))

U, s, Vh = np.linalg.svd(vecs, full_matrices=False)

# Plotting words and their vector representations

for i in range(len(words)):
    fig = plt.gcf()
    fig.set_size_inches(100, 100)
    plt.text(U[i, 0], U[i, 1], words[i])
    plt.xlim((-0.02, 0.02))
    plt.ylim((-0.04, 0.04))

plt.savefig('viz.png')
